# This file was generated by GoReleaser. DO NOT EDIT.
cask "asd" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "c9bd6588f4811f9d2c5bfec95e55c91df490f52af2546a74e39b5d86fdc4e31c"
      url "https://github.com/Mik1337/asd/releases/download/v#{version}/asd_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b821f7e4bce38e109c398ac4561e739584ba1aebe65220868798cfb0b049b34"
      url "https://github.com/Mik1337/asd/releases/download/v#{version}/asd_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "38de647d72b8815bca60912c7ab2405debbfd09ceb9cc3a5eca2700584d0af80"
      url "https://github.com/Mik1337/asd/releases/download/v#{version}/asd_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2bf01778c97f64640602526d8a00116af3725f861497f2c43320aee64a84739e"
      url "https://github.com/Mik1337/asd/releases/download/v#{version}/asd_linux_arm64.tar.gz"
    end
  end

  name "asd"
  desc "Translate a natural-language description into a shell command"
  homepage "https://github.com/Mik1337/asd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "asd"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/asd"]
    end
  end

  # No zap stanza required

end
