# This file was generated by GoReleaser. DO NOT EDIT.
cask "asd" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "a5353088d38f39092b1f7807a0bfa4689b157b2a21b74197eadd76978aafeeed"
      url "https://github.com/Mik1337/asd/releases/download/v#{version}/asd_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "414c1477e42db9baa8728391e271363fe791e4100b3bb610915c7bc87374c572"
      url "https://github.com/Mik1337/asd/releases/download/v#{version}/asd_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e694428d64aed6249544693979054e2a35ef2283cb43884a3c545ea5f9f995c6"
      url "https://github.com/Mik1337/asd/releases/download/v#{version}/asd_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "63d4db53b4227d6e9e7f70e7ab2608b0421ef0c1f4d949c667f92539f1219e14"
      url "https://github.com/Mik1337/asd/releases/download/v#{version}/asd_linux_arm64.tar.gz"
    end
  end

  name "asd"
  desc "Translate a natural-language description into a shell command"
  homepage "https://github.com/Mik1337/asd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "asd"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/asd"]
    end
  end

  # No zap stanza required

end
